providers: true
output:
  type: file
  dir: /repo/public
  basePath: '/openfed-libraries'
inputs:
  extdep:
    type: static
    packages:
      w8tcha/ckeditor-codemirror:
        v1.16:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/archive/1.16.tar.gz
          source:
            type: git
            url: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin.git
            reference: '1.16'
